### ISSUE TITLE
Adding element to arrays

### ISSUE THREAD

**Issue by gregdouglas** [grofit/aurelia-chart#5] opened 2016-03-25 18:29 UTC
I'm having an issue where graphs aren't updated if I add an element to the data array , after the chart has been bound. Is this a known issue?

**Comment by grofit** [comment] 2016-03-25 19:10
nope, can you create an isolated repro of the problem (on c9 or plunker or something)?

I imagine its probably something to do with aurelia not notifying of the array change or something, does it change ok if you just change the value of an existing part of the data?

**Comment by gregdouglas** [comment] 2016-03-25 19:11
Works fine if I just change a existing value. I will come up with an example.

**Comment by grofit** [comment] 2016-03-25 19:15
if it is purely just adding to the array that blows it up I will see if I can repro later or tomorrow, (got a hectic weekend).

**Comment by grofit** [comment] 2016-03-26 18:49
Right, there seem to be 2 problems, one is that it is currently only subscribing to properties of the objects not the objects themselves, so currently I am using:

```
let subscription = this.bindingEngine.propertyObserver(model, property).subscribe;
                    if(subscription)
                    {
                        subscriptions.push(subscription);
                    }
```

once iterated through each property it classes it as being "watched" and then continues until the observers fire, now the problem is an array is seen as a parent object and it goes inside of it rather than listening to changes on it, that may possibly be observable so that would fix one of the issues, the other issue is that currently I only know of `bindingEngine.propertyObserve` so in the case of a pie chart where the array is the root model I am not entirely sure if Aurelia supports an object level observe, if so I may not even need to do this whole looping through thing (a throwback to the knockout version).

So if you or anyone knows if there is a better way to subscribe to an object and all its children and listen for any changes I can do that, which should sort your problem... anyway its all doable I think, just need to find a nice way to do it.

**Comment by grofit** [comment] 2016-04-21 08:02
This should be fixed now, let me know if you still have the issue.

There is still another issue related to this which I am about to raise which is around dynamically added entries to the data will cause a refresh but would not internally be tracked.

If it is not fixed feel free to re-open.

**Closed as completed by grofit** 2016-04-21 08:02 UTC
Labels: bug, help wanted
